### ISSUE TITLE
Visual Studio'dan CLI Moduna Geçiş

### ISSUE THREAD

**Issue by alaminut** [mdemiryurek/react-tutorials#1]
Mesut özellikle tutorial tipi işler için VS gibi büyük bir ide yerine mümkün olduğuna çok terminal ve minimal text editörler kullanmanı öneririm.

Bir de React için webpack temelli babel transpiler kullanan modelleri incele derim. Daha bu akşam bununla ilgili bir template proje yükledim istersen incele:

[https://github.com/alaminut/react-boilerplate](https://github.com/alaminut/react-boilerplate)

React ile ilgili de elimden geldiğince destek olurum tutorial ile çözemediğin bir şeyler olursa sorabilirsin.

**Comment by mdemiryurek** [comment]
Hakan selam, tavsiyen için çok teşekkürler. Aslında VS kullanmamın sebebi; bilgisayarda IDE olarak sadece VS'nin olması ve kullanıcı yetkisinden dolayı herhangi bir program kuramıyor oluşumdu. Kullanıcı yetkisini aldım, bilgisayara VS Code kurdum ve çok rahatladım :)
